name: Build and push Docker image to GHCR

on:
  push:
    tags: ["v*"]

  workflow_dispatch:
    inputs:
      new-version-tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    # environment varioables for docker image metadata
    env:
      OWNER_LC: ""
      REPO_LC: ""
      VERSION_TAG: ""

    permissions:
      packages: write
      contents: read

  steps:

    - name: Check secret key
      run: echo ${{ secrets.EXAMPLESECRET }}

    - name: get the image version tag from either dispatch or ref
      run: |
        echo "VERSION_TAG=${ACTIVE_TAG,,}" >>${GITHUB_ENV}
      env:
        ACTIVE_TAG: '${{ inputs.new-version-tag || github.ref_name }}'
    - name: sanitise env data for docker image tagging
      run: |
        echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        echo "REPO_LC=${REPO,,}" >> ${GITHUB_ENV}
      env:
        OWNER: '${{ github.repository_owner }}'
        REPO: '${{ github.repository }}'
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # additional helper for multi-platform image build
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # additional helper
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # actual image building and pushing
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: 
        push: true
        tags: |
          ghcr.io/${{env.REPO_LC}}:latest
          ghcr.io/${{env.REPO_LC}}:${{env.VERSION_TAG}}
        secrets: |
          "github_token=${{ secrets.GITHUB_TOKEN }}"
    
